Add Chuvash layout
FossifyOrg/Keyboard pull request #33
Opened 2024-03-09 09:03 UTC by tenextractor

#### What is it?
- [ ] Bugfix
- [X] Feature
- [ ] Codebase improvement

#### Description of the changes in your PR
Added Chuvash layout. String "Chuvash" is hardcoded for now, I think that needs to be fixed by changing https://github.com/FossifyOrg/Commons

#### Before/After Screenshots/Screen Record
![image](https://github.com/FossifyOrg/Keyboard/assets/139619642/af08a6b5-98ad-4280-add5-70733e6d35c0)

#### Fixes the following issue(s)

- Fixes #32 

#### Acknowledgement
- [X] I read the [contribution guidelines](https://github.com/FossifyOrg/Keyboard/blob/main/CONTRIBUTING.md).

2024-03-09 09:08 UTC, Aga-C commented
> String "Chuvash" is hardcoded for now

You can quickly add it by yourself in Commons in https://github.com/FossifyOrg/Commons/blob/master/commons/src/main/res/values/strings.xml. When creating a pull request in Commons, please mention that it's for this one.

2024-03-09 09:44 UTC, tenextractor commented
> You can quickly add it by yourself in Commons in https://github.com/FossifyOrg/Commons/blob/master/commons/src/main/res/values/strings.xml. When creating a pull request in Commons, please mention that it's for this one.
Thanks, that has been done.

2024-04-08 16:30 UTC, tenextractor commented
When will this be merged?

2024-04-08 16:46 UTC, Aga-C commented
Before Keyboard is released, all PRs will be merged. But I don't know when it will happen. Please be patient.

2024-06-05 17:54 UTC, naveensingh commented
@tenextractor Do you speak these languages? I mean Chuvash, Hebrew and Esperanto.

2024-06-11 01:25 UTC, naveensingh requested changes

2024-06-11 01:25 UTC, naveensingh commented on app/src/main/res/xml/keys_letters_chuvash.xml
> +            app:topSmallNumber="0" />
These characters are already there in the `?123` number layout. We don't need to duplicate them here.

Also, please convert some of the less common characters into popup characters, it's always a good idea to fit all characters in 4 rows or under.

2024-06-11 01:25 UTC, naveensingh commented on app/src/main/res/xml/keys_letters_chuvash.xml
> +            app:keyWidth="9.275%p" />
Shift and Backspace should use 15% of the available space as done in other layouts.

2024-06-23 17:55 UTC, tenextractor commented
> Do you speak these languages? I mean Chuvash, Hebrew and Esperanto.

No, but I know their alphabets. The Hebrew and Esperanto layouts have been copied from Gboard, with minor changes, and the Chuvash layout is based on user feedback.

> Also, please convert some of the less common characters into popup characters, it's always a good idea to fit all characters in 4 rows or under.

I had asked the user for feedback on whether to add the example layout on the left (Й У Ӳ К Е Ӗ...), but they requested a bigger layout with all the keys visible. All of those letters are important, and we can't fit them in 4 rows. Is there any reason we need to use only 4 rows? Many languages in Gboard use 5 or more rows, like Thai for example.

2024-06-24 04:31 UTC, tenextractor commented
> Shift and Backspace should use 15% of the available space as done in other layouts.

But this makes the keys in the bottom row narrower and harder to press accurately. If there are fewer keys in the 3rd row, bigger Shift and Backspace would be good, but both the 2nd and 3rd row have 11 keys, including Shift and Backspace.

2024-06-24 04:37 UTC, tenextractor commented
> These characters are already there in the ?123 number layout. We don't need to duplicate them here.

The issue is that it's not feasible to add all the Chuvash letters in 4 rows, so a 5th row was added. But the 5th row only has 6 alphabet letters, so I added 4 symbols to balance the layout and allow all 10 digits to be accessible with popups.

If the digits aren't an issue, the symbols could be removed, but that would make the top row have only 6 keys.

2024-06-24 12:54 UTC, naveensingh commented
4 rows aren't mandatory or anything, just a design choice. I think I'll just merge this now and update the layout as needed upon user feedback.

2024-06-24 12:54 UTC, merged